obj-$(CONFIG_CRYPTO_SHA1_AWS_X86_64_SHANI) += sha1_block.o sha1-x86_64.o
obj-$(CONFIG_CRYPTO_SHA1_DYN_AWS_X86_64_SHANI) += sha1-aws-x86_64-shani.o
sha1-aws-x86_64-shani-objs := sha1_block.o sha1-x86_64.o

AFLAGS_sha1-x86_64.o := \
	-I$(srctree)/vendor/aws-lc/include
