testprogs-y := digest
TEST_CFLAGS = -I$(srctree)/modules/digest/sha3-ossl
LIBS_digest = modules/built-in.o

cmockatest-$(CONFIG_CMOCKA) := test_digest
CMOCKA_CFLAGS = -I$(srctree)/modules/digest/sha3-ossl
CMOCKA_LIBS_test_digest = modules/built-in.o
