obj-$(CONFIG_CRYPTO_SHA3) += digest/sha3/
obj-$(CONFIG_CRYPTO_SHA3_DYN_C) += digest/sha3/

obj-$(CONFIG_CRYPTO_SHA3_NULL) += digest/sha3-null/
obj-$(CONFIG_CRYPTO_SHA3_DYN_NULL) += digest/sha3-null/

obj-$(CONFIG_CRYPTO_SHA3_OSSL) += digest/sha3-ossl/
obj-$(CONFIG_CRYPTO_SHA3_DYN_OSSL) += digest/sha3-ossl/

obj-$(CONFIG_CRYPTO_SHA3_ASM) += digest/sha3-aws/
obj-$(CONFIG_CRYPTO_SHA3_DYN_ASM) += digest/sha3-aws/

obj-$(CONFIG_CRYPTO_SHA1_NULL) += digest/sha1-null/
obj-$(CONFIG_CRYPTO_SHA1_DYN_NULL) += digest/sha1-null/

obj-$(CONFIG_CRYPTO_SHA1_OSSL) += digest/sha1-ossl/
obj-$(CONFIG_CRYPTO_SHA1_DYN_OSSL) += digest/sha1-ossl/

obj-$(CONFIG_CRYPTO_SHA1_ASM) += digest/sha1-aws/
obj-$(CONFIG_CRYPTO_SHA1_DYN_ASM) += digest/sha1-aws/

obj-$(CONFIG_CRYPTO_SHA2_NULL) += digest/sha2-null/
obj-$(CONFIG_CRYPTO_SHA2_DYN_NULL) += digest/sha2-null/

obj-$(CONFIG_CRYPTO_SHA2_OSSL) += digest/sha2-ossl/
obj-$(CONFIG_CRYPTO_SHA2_DYN_OSSL) += digest/sha2-ossl/

obj-$(CONFIG_CRYPTO_SHA2_ASM) += digest/sha2-aws/
obj-$(CONFIG_CRYPTO_SHA2_DYN_ASM) += digest/sha2-aws/
