ifdef CONFIG_CRYPTO_SHA3_OSSL
USERINCLUDE += -I$(srctree)/modules/digest/sha3-ossl
endif

ifdef CONFIG_CRYPTO_SHA1_OSSL
USERINCLUDE += -I$(srctree)/modules/digest/sha1-ossl
endif

ifdef CONFIG_CRYPTO_SHA2_OSSL
USERINCLUDE += -I$(srctree)/modules/digest/sha2-ossl
endif
