obj-$(CONFIG_CRYPTO_SHA2_OSSL_ARMV8) += sha256_block.o sha512_block.o sha256-armv8.o sha512-armv8.o armcap.o
obj-$(CONFIG_CRYPTO_SHA2_DYN_OSSL_ARMV8) += sha2-ossl-armv8.o
sha2-ossl-armv8-objs := sha256_block.o sha512_block.o sha256-armv8.o sha512-armv8.o armcap.o

OSSL_SHA_ASM := $(objtree)/vendor/openssl/crypto/sha

AFLAGS_sha256-armv8.o := -I$(srctree)/vendor/openssl/crypto
AFLAGS_sha512-armv8.o := -I$(srctree)/vendor/openssl/crypto
$(OSSL_SHA_ASM)/sha256-armv8.S: $(srctree)/vendor/openssl/crypto/sha/asm/sha512-armv8.pl
	@mkdir -p $(dir $@)
	$(PERL) $< linux64 $@
$(OSSL_SHA_ASM)/sha512-armv8.S: $(srctree)/vendor/openssl/crypto/sha/asm/sha512-armv8.pl
	@mkdir -p $(dir $@)
	$(PERL) $< linux64 $@
$(obj)/sha256-armv8.o: $(OSSL_SHA_ASM)/sha256-armv8.S
	$(call cmd,as_o_S)
$(obj)/sha512-armv8.o: $(OSSL_SHA_ASM)/sha512-armv8.S
	$(call cmd,as_o_S)
$(obj)/armcap.o: $(srctree)/modules/cpu/arm-ossl/cap.c
	$(call cmd,cc_o_c)

CFLAGS_sha256_block.o := \
	-I$(srctree)/modules/digest/sha2-ossl-armv8 \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA256_ASM

CFLAGS_sha512_block.o := \
	-I$(srctree)/modules/digest/sha2-ossl-armv8 \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA512_ASM
