obj-$(CONFIG_CRYPTO_SHA2_OSSL_X86_64) += sha256_block.o sha512_block.o sha256-x86_64.o sha512-x86_64.o ossl_x86cap.o
obj-$(CONFIG_CRYPTO_SHA2_DYN_OSSL_X86_64) += sha2-ossl-x86_64.o
sha2-ossl-x86_64-objs := sha256_block.o sha512_block.o sha256-x86_64.o sha512-x86_64.o ossl_x86cap.o

OSSL_SHA_ASM := $(objtree)/vendor/openssl/crypto/sha

$(obj)/sha256-x86_64.o: $(OSSL_SHA_ASM)/sha256-x86_64.s
	$(call cmd,ossl_as_o_S)
$(obj)/sha512-x86_64.o: $(OSSL_SHA_ASM)/sha512-x86_64.s
	$(call cmd,ossl_as_o_S)
$(obj)/ossl_x86cap.o: $(srctree)/modules/cpu/x86-ossl/cap.c
	$(call cmd,cc_o_c)

CFLAGS_sha256_block.o := \
	-I$(srctree)/modules/digest/sha2-ossl-x86_64 \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA256_ASM

CFLAGS_sha512_block.o := \
	-I$(srctree)/modules/digest/sha2-ossl-x86_64 \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA512_ASM
