# AES-128/256 (CBC, GCM)
obj-$(CONFIG_CRYPTO_CIPHER_AES_GENERIC) += aes/
obj-$(CONFIG_CRYPTO_CIPHER_AES_DYN_GENERIC) += aes/
obj-$(CONFIG_CRYPTO_CIPHER_AES_AWS_X86_64) += aes-aws-x86_64/
obj-$(CONFIG_CRYPTO_CIPHER_AES_DYN_AWS_X86_64) += aes-aws-x86_64/
obj-$(CONFIG_CRYPTO_CIPHER_AES_AWS_ARMV8) += aes-aws-armv8/
obj-$(CONFIG_CRYPTO_CIPHER_AES_DYN_AWS_ARMV8) += aes-aws-armv8/

# ChaCha20-Poly1305 (RFC 7539)
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_GENERIC) += chacha/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_DYN_GENERIC) += chacha/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_AWS_X86_64) += chacha-aws-x86_64/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_DYN_AWS_X86_64) += chacha-aws-x86_64/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_AWS_ARMV8) += chacha-aws-armv8/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_DYN_AWS_ARMV8) += chacha-aws-armv8/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_AWS_FUSED_ARMV8) += chacha-aws-fused-armv8/
obj-$(CONFIG_CRYPTO_CIPHER_CHACHA20_DYN_AWS_FUSED_ARMV8) += chacha-aws-fused-armv8/

# The TLS 1.0/1.1 era. One backend each, no acceleration, off by default:
# these exist to read the 3DES and RC4 suites of that traffic.
obj-$(CONFIG_CRYPTO_CIPHER_DES3) += des3/
obj-$(CONFIG_CRYPTO_CIPHER_DES3_DYN) += des3/

obj-$(CONFIG_CRYPTO_CIPHER_RC4) += rc4/
obj-$(CONFIG_CRYPTO_CIPHER_RC4_DYN) += rc4/
