obj-$(CONFIG_CRYPTO_SHA2_OSSL) += sha256_block.o sha512_block.o
obj-$(CONFIG_CRYPTO_SHA2_DYN_OSSL) += sha2-ossl.o
sha2-ossl-objs := sha256_block.o sha512_block.o

OSSL_SHA_ASM := $(objtree)/vendor/openssl/crypto/sha

ifeq ($(SRCARCH),arm64)
obj-$(CONFIG_CRYPTO_SHA2_OSSL) += sha256-armv8.o sha512-armv8.o armcap.o
sha2-ossl-objs += sha256-armv8.o sha512-armv8.o armcap.o
AFLAGS_sha256-armv8.o := -I$(srctree)/vendor/openssl/crypto
AFLAGS_sha512-armv8.o := -I$(srctree)/vendor/openssl/crypto
$(obj)/sha256-armv8.o: $(OSSL_SHA_ASM)/sha256-armv8.S
	$(call cmd,as_o_S)
$(obj)/sha512-armv8.o: $(OSSL_SHA_ASM)/sha512-armv8.S
	$(call cmd,as_o_S)
$(obj)/armcap.o: $(srctree)/modules/cpu/arm-ossl/cap.c
	$(call cmd,cc_o_c)
endif

ifeq ($(SRCARCH),x86)
obj-$(CONFIG_CRYPTO_SHA2_OSSL) += sha256-x86_64.o sha512-x86_64.o ossl_x86cap.o
sha2-ossl-objs += sha256-x86_64.o sha512-x86_64.o ossl_x86cap.o
$(obj)/sha256-x86_64.o: $(OSSL_SHA_ASM)/sha256-x86_64.s
	$(call cmd,ossl_as_o_S)
$(obj)/sha512-x86_64.o: $(OSSL_SHA_ASM)/sha512-x86_64.s
	$(call cmd,ossl_as_o_S)
$(obj)/ossl_x86cap.o: $(srctree)/modules/cpu/x86-ossl/cap.c
	$(call cmd,cc_o_c)
endif

CFLAGS_sha256_block.o := \
	-I$(srctree)/modules/xdg/sha2-ossl \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA256_ASM

CFLAGS_sha512_block.o := \
	-I$(srctree)/modules/xdg/sha2-ossl \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA512_ASM
