obj-$(CONFIG_CRYPTO_SHA1_AWS_ARMV8) += sha1_block.o sha1-armv8.o
obj-$(CONFIG_CRYPTO_SHA1_DYN_AWS_ARMV8) += sha1-aws-armv8.o
sha1-aws-armv8-objs := sha1_block.o sha1-armv8.o

AFLAGS_sha1-armv8.o := \
	-I$(srctree)/vendor/aws-lc/include
