obj-$(CONFIG_CRYPTO_SHA2_ASM) += sha256_block.o sha512_block.o
obj-$(CONFIG_CRYPTO_SHA2_DYN_ASM) += sha2-aws.o
sha2-aws-objs := sha256_block.o sha512_block.o

ifeq ($(SRCARCH),arm64)
obj-$(CONFIG_CRYPTO_SHA2_ASM) += sha256-armv8.o sha512-armv8.o
sha2-aws-objs += sha256-armv8.o sha512-armv8.o
endif

ifeq ($(SRCARCH),x86)
obj-$(CONFIG_CRYPTO_SHA2_ASM) += sha256-x86_64.o sha512-x86_64.o
sha2-aws-objs += sha256-x86_64.o sha512-x86_64.o
endif

AFLAGS_sha256-armv8.o := \
	-I$(srctree)/vendor/aws-lc/include

AFLAGS_sha512-armv8.o := \
	-I$(srctree)/vendor/aws-lc/include

AFLAGS_sha256-x86_64.o := \
	-I$(srctree)/vendor/aws-lc/include

AFLAGS_sha512-x86_64.o := \
	-I$(srctree)/vendor/aws-lc/include
