obj-$(CONFIG_CRYPTO_SHA2_AWS_X86_64_AVX2) += sha256-x86_64.o sha512-x86_64.o
obj-$(CONFIG_CRYPTO_SHA2_DYN_AWS_X86_64_AVX2) += sha2-aws-x86_64-avx2.o
sha2-aws-x86_64-avx2-objs := sha256-x86_64.o sha512-x86_64.o

AFLAGS_sha256-x86_64.o := -I$(srctree)/vendor/aws-lc/include
AFLAGS_sha512-x86_64.o := -I$(srctree)/vendor/aws-lc/include
