# Camellia (CBC, GCM), for the *_WITH_CAMELLIA_* suites of RFC 5932 and
# RFC 6367. One backend, portable C, off by default. GCM is the mode written
# once in ../gcm, compiled here over this block cipher (gcm-backend.h).
MODE_GCM := $(srctree)/$(CRYPTO_DIR)/modules/cipher/gcm

obj-$(CONFIG_CRYPTO_CIPHER_CAMELLIA) += camellia.o gcm.o
obj-$(CONFIG_CRYPTO_CIPHER_CAMELLIA_DYN) += cipher-camellia.o
cipher-camellia-objs := module.o camellia.o gcm.o

$(obj)/gcm.o: $(MODE_GCM)/gcm.c FORCE
	$(call if_changed_rule,cc_o_c)

CFLAGS_gcm.o := -I$(srctree)/$(CRYPTO_DIR)/modules/cipher/camellia \
		-DGCM_ENCRYPT_AAD=camellia_gcm_encrypt_aad \
		-DGCM_DECRYPT_AAD=camellia_gcm_decrypt_aad \
		-DGCM_ENCRYPT=camellia_gcm_encrypt \
		-DGCM_DECRYPT=camellia_gcm_decrypt
