obj-$(CONFIG_CRYPTO_SHA1_OSSL) += sha1_block.o
obj-$(CONFIG_CRYPTO_SHA1_DYN_OSSL) += sha1-ossl.o
sha1-ossl-objs := sha1_block.o

OSSL_SHA_ASM := $(objtree)/vendor/openssl/crypto/sha

ifeq ($(SRCARCH),arm64)
obj-$(CONFIG_CRYPTO_SHA1_OSSL) += sha1-armv8.o ossl_armcap.o
sha1-ossl-objs += sha1-armv8.o ossl_armcap.o
AFLAGS_sha1-armv8.o := -I$(srctree)/vendor/openssl/crypto
$(obj)/sha1-armv8.o: $(OSSL_SHA_ASM)/sha1-armv8.S
	$(call cmd,as_o_S)
$(obj)/ossl_armcap.o: $(srctree)/modules/cpu/arm-ossl/cap.c
	$(call cmd,cc_o_c)
endif

ifeq ($(SRCARCH),x86)
obj-$(CONFIG_CRYPTO_SHA1_OSSL) += sha1-x86_64.o ossl_x86cap.o
sha1-ossl-objs += sha1-x86_64.o ossl_x86cap.o
$(obj)/sha1-x86_64.o: $(OSSL_SHA_ASM)/sha1-x86_64.s
	$(call cmd,ossl_as_o_S)
$(obj)/ossl_x86cap.o: $(srctree)/modules/cpu/x86-ossl/cap.c
	$(call cmd,cc_o_c)
endif

CFLAGS_sha1_block.o := \
	-I$(srctree)/modules/digest/sha1-ossl \
	-I$(srctree)/vendor/openssl/include \
	-I$(srctree)/vendor/openssl \
	-I$(objtree)/vendor/openssl/include \
	-DSHA1_ASM
